export const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";

export const ROTOR_I = "EKMFLGDQVZNTOWYHXUSPAIBRCJ";

export const ROTOR_II = "AJDKSIRUXBLHWTMCQGZNPYFVOE";

export const ROTOR_III = "BDFHJLCPRTXVZNYEIWGAKMUSQO";

export const REFLECTOR_B = "YRUHQSLDPXNGOKMIEBFZCWVJAT";